name: 'Update Release Branch'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x

        - name: Publish
          run: dotnet publish WebClient/WebClient.csproj --configuration Release --output build

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v4
          with:
            token: ${{ secrets.ACCESS_TOKEN }}
            branch: release
            folder: build/wwwroot 
            single-commit: true