name: 'Update Release Branch'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x

        - name: Publish
          run: dotnet publish WebClient/WebClient.csproj --configuration Release

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v4
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BASE_BRANCH: master
            BRANCH: release
            FOLDER: WebClient/bin/Release/net5.0/publish/wwwroot 
            SINGLE_COMMIT: true