name: 'Update Release Branch'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.x

        - name: Publish
          run: dotnet publish WebClient/WebClient.csproj --configuration Release

        - name: Release
          if: ${{ github.ref == 'refs/heads/main' }}
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: release
            publish_dir: WebClient/bin/Release/net5.0/browser-wasm/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true